<letter> ::= a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|
             A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z

<digit> ::= 0|1|2|3|4|5|6|7|8|9

<word> ::= <word> <letter> |
           <word> <digit> |
           <word> '_' |
           <letter> |
           <digit>

<redirection> ::= '<' <word> |
                  '>' <word> |
                  '>>' <word>

<simple_command_element> ::= <word> |
                             <redirection>

<simple_command> ::= <word> (<simple_command_element>)*

<list0> ::= <list1> '&' |
            <list1> ';'

<list1> ::= <list1> '&' <list1> |
            <list1> ';' <list1> |
            <list1> '&&' <list1> |
            <list1> '||' <list1> |
            <pipeline>

<pipeline> ::= <pipeline> '|' <pipeline> |
               <simple_command> |
               <subshell>

<subshell> ::= '(' <command> ')' (<redirection>)*

<command> ::= <list1> |
              <list0>
