TESTDIR = test
TESTBUILDDIR = $(TESTDIR)/build
TESTMODULES = str.c wordlist.c line.c line_process_char.c
TESTS = $(addprefix $(TESTBUILDDIR)/,$(TESTMODULES:%.c=%))

$(TESTBUILDDIR)/%: $(TESTDIR)/%.c $(OBJS)
	$(CC) $(CFLAGS) $^ -o $@

$(TESTS): | $(TESTBUILDDIR)

$(TESTBUILDDIR):
	mkdir -p $@

unittests: $(TESTS)
	for test in $^; do ./$$test; done

test: unittests $(TARGET)
	./test_dish.sh $(TARGET) $(TESTDIR)/data
