TEST_BIN_DIR = $(BIN_DIR)/test

TEST_DIR = test

TEST_UNIT_DIR = $(TEST_DIR)/unit
TEST_UNIT_MODULES = str.c wordlist.c line.c line_process.c
TEST_UNITS = $(TEST_UNIT_MODULES:%.c=$(TEST_BIN_DIR)/%)

TEST_FRAMEWORK = unity
TEST_FRAMEWORK_SRC = $(LIB_DIR)/$(TEST_FRAMEWORK)/src/unity.c
TEST_FRAMEWORK_INCLUDE = -isystem $(LIB_DIR)/$(TEST_FRAMEWORK)/src


# dependent directories
$(TEST_BIN_DIR):
	mkdir -p $@

$(TEST_UNITS): | $(TEST_BIN_DIR)


# unit testing framework
$(LIB_DIR)/$(TEST_FRAMEWORK): | $(LIB_DIR)
	git clone https://github.com/ThrowTheSwitch/Unity.git $@


# tests
$(TEST_BIN_DIR)/%: $(TEST_UNIT_DIR)/%.c $(TEST_FRAMEWORK_SRC) $(OBJS)
	$(CC) $(TEST_FRAMEWORK_INCLUDE) $(CFLAGS) $^ -o $@


unittests: $(TEST_UNITS)
	for test in $^; do echo "\n*****TEST $$test*****"; ./$$test; done

tests: $(TARGET) unittests
	./test_dish.sh $< $(TEST_DIR)/data
