name: DiShell Tests

on:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Updating submodules
        run: make submodules

      - name: Setting up a Unity testing framework
        run: make unity

      - name: Make unittests
        run: make unittests

      - name: Make functests
        run: make functests
